/**
 * Created by huangzhangshu on 2018/2/26
 */

// 用户管理常量
export const Field = {
  PASSWORD_ERROR: '密码输入不一致！',
  DOMAIN_LABEL: '组织：',
  EMP_USER_LABEL: '职工：',
  DOMAIN_RULE_MESSAGE: '请选择组织',
  NOT_FOUND_DOMAIN: '暂无组织',
  NOT_FOUND_EMP_USER: '暂无职工',
  NOT_FOUND_USER_TYPE: '暂无用户类型',
  NOT_FOUND_USER_CATEGORY: '暂无用户级别',
  DOMAIN_PLACEHOLDER: '请选择组织',
  USER_TYPE_PLACEHOLDER: '请选择用户类型',
  USER_CATEGORY_PLACEHOLDER: '请选择用户级别',
  USERNAME_RULE_MESSAGE: '请输入用户名',
  USER_TYPE_MESSAGE: '请输入用户类型',
  USER_TYPE_CATEGORY: '请选择用户级别',
  USER_TYPE_DESCRIPTION: '请输入描述',
  EMP_USER_PLACEHOLDER: '请选择职工',
  EMP_USER_ERROR_MESSAGE: '请选择职工',
  USERNAME_LABEL: '用户名：',
  PASSWORD_LABEL: '密码',
  PASSWORD_REQUIRED: '请输入密码!',
  CONFIRM_PASSWORD_LABEL: '密码确认',
  CONFIRM_PASSWORD_REQUIRED: '请再次输入密码',
  NAME_LABEL: '姓名：',
  NAME_RULE_MESSAGE: '请输入姓名',
  EMAIL_LABEL: '电子邮箱：',
  EMAIL_RULE_MESSAGE: '请输入正确格式的电子邮箱',
  MOBILE_LABEL: '手机号：',
  DESCRIBE_LABEL: '描述：',
  STATUS_LABEL: '状态：',
  STATUS_ENABLED: '启用',
  STATUS_DISABLED: '停用',
  ROLE_LABEL: '角色:',
  CLOSE: '取消',
  SAVE: '保存',
  CREATE_USER_TITLE: '新增用户',
  UPDATE_USER_TITLE: '修改用户信息',
  DOMAIN_AUTO_PLACEHOLDER: '选择组织',
  USER_DELETE_TITLE: '确定删除选中数据吗?',
  CANCEL: '取消',
  OK: '确定',
  DELETE: '删除',
  SEARCH: '查询',
  ADD_USER: '新增',
  ALLOCATION_ROLE: '分配角色',
  BATCH_ALLOCATION_ROLE: '批量分配角色',
  DOMAIN_NAME: '组织机构: ',
  USER_NAME: '用户名: ',
  ROLE_NAME: '角色:',
  ROLE_TYPE: '角色类型:',
  USER_NAME2: '用户: ',
  UNIT_NAME: '组织: ',
  SYSTEM_NAME: '系统: ',
  ACCOUNT_NAME: '账套: ',
  DOMAIN_NAME_PLACEHOLDER: '请输入组织机构',
  USER_NAME_PLACEHOLDER: '请输入用户名',
  ROLE_NAME_PLACEHOLDER: '请输入角色',
  UNIT_PLACEHOLDER: '请输入组织',
  SYSTEM_PLACEHOLDER: '请输入系统',
  ACCOUNT_PLACEHOLDER: '请输入账套',
  RESET_PASSWORD: '初始化密码',
  USER_DESCRIPTION: '用户描述',
  USER_TYPE: '类型:',
  USER_DEPT: '部门:',
  USER_UNIT: '组织:',
  USER_STATUS: '服务状态',
  USER_STATUS_NAME: '服务状态',
  USER_SEARCH_NAME: '用户:',
  SSO_TYPE: '注册状态',
};

export const TYPE_DATA = {
  0: '普通员工',
  1: '管理员',
};
