import cloneDeep from 'lodash/cloneDeep'
/**
 * reducers
 */
const initState = {
  // units: [
  //   {
  //     accManager: null,
  //     activeFlag: "1",
  //     address: null,
  //     adminArea: null,
  //     areaCode: null,
  //     budgetCode: null,
  //     city: null,
  //     code: "1001",
  //     compLeader: null,
  //     compLevel: 1,
  //     compLevelCode: "01",
  //     compTypeCode: null,
  //     createdBy: "admin",
  //     creationDate: 1655955463083,
  //     deletionDate: null,
  //     description: null,
  //     disEmail: null,
  //     fullName: null,
  //     highLine: null,
  //     hospAttrCode: null,
  //     hospLevelCode: "100101",
  //     id: "8a80bed1818e5d9401818ea31bb60010",
  //     institutionTypeCode: null,
  //     instype: "1",
  //     isCount: "0",
  //     isEnabled: "1",
  //     isGroup: null,
  //     isLast: "0",
  //     lastUpdateDate: 1655955463083,
  //     lastUpdatedBy: "admin",
  //     linkPhone: null,
  //     linkman: null,
  //     lowLine: null,
  //     name: "AT望海医院",
  //     orgfullname: null,
  //     orgtypecode: null,
  //     postCode: null,
  //     prov: null,
  //     spell: "ATWHYY",
  //     subjectionCode: null,
  //     superCode: "1",
  //     taxNo: null,
  //     timeBegin: 1655955463083,
  //     timeEnd: null,
  //     typeCode: null,
  //     typeId: null,
  //     u_id: 0,
  //     unitCode: null,
  //     uuid: "9023ef6bdf8c4c2683e6d22cb491f330",
  //   },
  //   {
  //     accManager: null,
  //     activeFlag: "1",
  //     address: null,
  //     adminArea: "",
  //     areaCode: "110101",
  //     budgetCode: null,
  //     city: "110101",
  //     code: "100151",
  //     compLeader: null,
  //     compLevel: 2,
  //     compLevelCode: "01",
  //     compTypeCode: null,
  //     createdBy: "admin",
  //     creationDate: 1655958565933,
  //     deletionDate: null,
  //     description: null,
  //     disEmail: null,
  //     fullName: null,
  //     highLine: null,
  //     hospAttrCode: null,
  //     hospLevelCode: "100101",
  //     id: "8a80bed1818e5d9401818ed2742e0f99",
  //     institutionTypeCode: null,
  //     instype: "1",
  //     isCount: "0",
  //     isEnabled: "1",
  //     isGroup: null,
  //     isLast: "1",
  //     lastUpdateDate: 1655958565933,
  //     lastUpdatedBy: "admin",
  //     linkPhone: null,
  //     linkman: null,
  //     lowLine: null,
  //     name: "AT成本医院51",
  //     orgfullname: null,
  //     orgtypecode: null,
  //     postCode: null,
  //     prov: "110000",
  //     spell: "ATCBYY51",
  //     subjectionCode: null,
  //     superCode: "1001",
  //     taxNo: null,
  //     timeBegin: 1655958565933,
  //     timeEnd: null,
  //     typeCode: null,
  //     typeId: null,
  //     u_id: 0,
  //     unitCode: null,
  //     uuid: "01553b24be944085a79c5ace49fef795",
  //   }
  // ],
  // currentUnit: {
  //   accManager: null,
  //   activeFlag: "1",
  //   address: null,
  //   adminArea: null,
  //   areaCode: null,
  //   budgetCode: null,
  //   city: null,
  //   code: "1001",
  //   compLeader: null,
  //   compLevel: 1,
  //   compLevelCode: "01",
  //   compTypeCode: null,
  //   createdBy: "admin",
  //   creationDate: 1655955463083,
  //   deletionDate: null,
  //   description: null,
  //   disEmail: null,
  //   fullName: null,
  //   highLine: null,
  //   hospAttrCode: null,
  //   hospLevelCode: "100101",
  //   id: "8a80bed1818e5d9401818ea31bb60010",
  //   institutionTypeCode: null,
  //   instype: "1",
  //   isCount: "0",
  //   isEnabled: "1",
  //   isGroup: null,
  //   isLast: "0",
  //   lastUpdateDate: 1655955463083,
  //   lastUpdatedBy: "admin",
  //   linkPhone: null,
  //   linkman: null,
  //   lowLine: null,
  //   name: "AT望海医院",
  //   orgfullname: null,
  //   orgtypecode: null,
  //   postCode: null,
  //   prov: null,
  //   spell: "ATWHYY",
  //   subjectionCode: null,
  //   superCode: "1",
  //   taxNo: null,
  //   timeBegin: 1655955463083,
  //   timeEnd: null,
  //   typeCode: null,
  //   typeId: null,
  //   u_id: 0,
  //   unitCode: null,
  //   uuid: "9023ef6bdf8c4c2683e6d22cb491f330",
  // },
  // size: {
  //   height: 463.6000061035156,
  //   position: null,
  //   width: 1504,
  // },
  // currentApp: {
  //   account: "",
  //   acct: "",
  //   icon: "",
  //   id: "sys",
  //   isAccount: false,
  //   isDisplay: true,
  //   name: "系统管理平台",
  //   order: "100",
  //   path: null,
  // },
  // theme: "light",
};

export default {
  namespace: 'global',
  state: cloneDeep(initState),
  effects: {},
  reducers: {
    update(state, {payload}) {
      return {...state, ...payload};
    },
  },
};
